apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.facade.config.name}}
data:
  SERVER_TEST_INSTANCE: "http://{{.Values.test.service.name}}:{{.Values.test.port}}"
  SERVER_PORT: "{{.Values.facade.port}}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.facade.name" . }}      #название пода
  labels:
    environment: "dev"
    release: "stable"
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    app: {{ include "app-chart.facade.name" . }}
spec:
  replicas: 1             #количество реплик
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      environment: "dev"
      release: "stable"
      chart: {{.Chart.Name}}-{{.Chart.Version}}
      app: {{ include "app-chart.facade.name" . }}
  template:
    metadata:
      labels:
        environment: "dev"
        release: "stable"
        chart: {{.Chart.Name}}-{{.Chart.Version}}
        app: {{ include "app-chart.facade.name" . }}
    spec:
      containers:
        - name: {{ include "app-chart.facade.name" . }}
          image: {{.Values.facade.image.name}}:{{.Values.facade.image.tag}}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{.Values.facade.config.name}}   #Ссылаемся на уже созданный ConfigMap
          ports:
            - containerPort: {{.Values.facade.port}}
              protocol: TCP
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5  #задежка перед первой проверкой
#            periodSeconds: 3        #интервал между проверками
#          resources:
#            limits:
#              memory: "256Mi"
#              cpu: "200m"
#            requests:
#              memory: "128Mi"
#              cpu: "50m"

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.facade.service.name}}
  labels:
    environment: "dev"
    release: "stable"
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    app: {{.Values.facade.service.name}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{.Values.facade.port}}        #выходной порт сервиса
      protocol: TCP
      targetPort: {{.Values.facade.port}}  #порт облуживаемых подов http://facade-service:8080
  selector:
    environment: "dev"
    release: "stable"
    app: {{ include "app-chart.facade.name" . }}       #название приложения

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.facade.service.name}}-out
  labels:
    environment: "dev"
    release: "stable"
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    app: {{.Values.facade.service.name}}-out
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: {{.Values.facade.port}}
  selector:
    environment: "dev"
    release: "stable"
    app: {{ include "app-chart.facade.name" . }}       #название приложения
  type: NodePort