test:
  deployment:
    name:
    replicas: 1
  container:
    name:
    resources: {}
  service:
    name:
    port: 8080
  image:
    name: dobrovolskiy/cloud-test
    tag: latest
    pullPolicy: IfNotPresent
  hpa:
    enabled: false
    name:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75

---

gateway:
  deployment:
    name:
    replicas: 1
  container:
    name:
    resources: {}
  service:
    name:
    port: 80
    type: LoadBalancer
  image:
    name: ddobrovolskiy/cloud-facade
    tag: latest
    pullPolicy: IfNotPresent
  hpa:
    enabled: false
    name:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
