server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful
instance:
  test: ${SERVER_TEST_INSTANCE:http://localhost:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true