test:
  name: test
  service:
    name: test-service
  image:
    name: ddobrovolskiy/cloud-test
    tag: 0.0.4
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 75
  config:
    name: test-config
    config: config-config
  secret:
    name: test-secret
    secret: secret-secret
  port: 8080

facade:
  name: facade
  service:
    name: facade-service
  image:
    name: ddobrovolskiy/cloud-facade
    tag: 0.0.2
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 75
  config:
    name: facade-config
  port: 8080
