apiVersion: v1
kind: Service
metadata:
  labels:
    tier: facade-service
  name: facade-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080        #выходной порт сервиса
      protocol: TCP
      targetPort: 8080  #порт облуживаемых подов http://facade-service:8080
  selector:
    tier: facade-service