apiVersion: v1
kind: Service
metadata:
  labels:
    tier: test-service
  name: test-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080        #выходной порт сервиса
      protocol: TCP
      targetPort: 8080  #порт облуживаемых подов
  selector:
    tier: test-service