apiVersion: v1
kind: Service
metadata:
  labels:
    tier: test-service
  name: test-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080        #выходной порт сервиса
      protocol: TCP
      targetPort: 8080  #порт облуживаемых подов
  selector:
    tier: test-service

---

apiVersion: v1
kind: Service
metadata:
  labels:
    tier: facade-service
  name: facade-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080        #выходной порт сервиса
      protocol: TCP
      targetPort: 8080  #порт облуживаемых подов http://facade-service:8080
  selector:
    tier: facade-service

---

apiVersion: v1
kind: Service
metadata:
  labels:
    tier: facade-service
  name: facade-service-out
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    tier: facade-service
  type: NodePort