apiVersion: v1
kind: Service
metadata:
  labels:
    tier: facade-service
  name: facade-service-out
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    tier: facade-service
  type: NodePort